models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use yii\db\ActiveRecord;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;

    const ROLE_USER=1;
    const ROLE_ADMISION=2;
    const ROLE_ADMIN=3;
    const ROLE_SUPER_ADMIN=4;

    const SALT="HacNNdqKYmceDFHHDGBVIvcuLXJPfPUH";

    public static function tableName()
    {
        return 'users';
    }
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return self::findOne(array('id'=>$id));
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    public static function isUserAdmin($username)
    {
        if (static::findOne(['login' => $username, 'role' => self::ROLE_ADMIN]))
            return true;

        return false;
    }

    public static function isUserOrAdmission($username,$role)
    {
        switch ($role){
            case 1:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_USER]))
                    return true;
                break;
            case 2:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_ADMISION]))
                    return true;
                break;
            case 4:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_SUPER_ADMIN]))
                    return true;
                break;
            default: return false;
            break;
        }
    }


    public static function findByLogin($login)
    {
        //return User::find()->where(['email' => $email, 'status' => self::STATUS_ACTIVE])->one();
        return self::findOne(['login' => $login]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(['login' => $username]);
//        foreach (self::$users as $user) {
//            if (strcasecmp($user['username'], $username) === 0) {
//                return new static($user);
//            }
//        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        //return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        if (Yii::$app->getSecurity()->validatePassword($password, $this->password))
            return true;
        return false;

    }

    public function getFullname()
    {
        $profile = static::find()->where(['id'=>Yii::$app->user->identity->id])->one();
        if ($profile !=null)
            return $profile->name.' '.$profile->lname.' '.$profile->oname;
        else return "Not Autorized";
        return false;
    }

    public function getLevel()
    {
        return $this->hasMany(Level::className(), ['id_user' => 'id']);
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $genauto
 * @property string $name
 * @property string $lname
 * @property string $oname
 * @property string $date_birth
 * @property string $email
 * @property integer $sex
 * @property string $passport_number
 * @property string $where_passport
 * @property string $date_passport
 * @property integer $id_city
 * @property integer $sp_int
 * @property integer $sp_unique
 * @property integer $datecreate
 * @property integer $lastupdate
 * @property integer $role
 * @property integer $status
 *
 * @property Balance[] $balances
 * @property Balance[] $balances0
 * @property City $idCity
 */
class Users extends \yii\db\ActiveRecord
{
    public $sp_unique;
    public $sp_int;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login', 'password', 'name', 'lname', 'datecreate', 'lastupdate', 'role', 'status','genauto','email'], 'required','on'=>'registrAdmin'],
            [['sex', 'id_city', 'sp_int', 'sp_unique', 'datecreate', 'lastupdate', 'role', 'status','passport_number','where_passport','phone','date_birth','email','date_passport','login','address', 'name', 'lname'], 'required','on'=>'registrUser'],
            [['sex', 'id_city', 'datecreate', 'lastupdate', 'role', 'status','passport_number','where_passport','phone','date_birth','email','date_passport','login','address', 'name', 'lname'], 'required','on'=>'updateUser'],
            [['date_birth', 'email', 'date_passport'], 'safe'],
            [['email'], 'email'],
            ['login', 'unique'],
            ['email', 'unique'],
            ['inn', 'unique'],
            [['date_birth','date_passport'], 'date', 'format' => 'yyyy-mm-dd','on'=>'registrUser'],
            [['date_birth','date_passport'], 'date', 'format' => 'yyyy-mm-dd','on'=>'updateUser'],

            [['sex', 'id_city', 'sp_int', 'sp_unique', 'datecreate', 'lastupdate', 'role', 'status','inn'], 'integer'],
            [['login', 'name', 'lname', 'oname','phone'], 'string', 'max' => 50],
            [['password','genauto','address'], 'string', 'max' => 255],
            [['passport_number'], 'string', 'max' => 20],
            [['where_passport','email'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Логин',
            'password' => 'Пароль',
            'genauto' => 'Пароль',
            'address' => 'Адрес',
            'name' => 'Имя',
            'lname' => 'Фамилия',
            'oname' => 'Отчества',
            'date_birth' => 'День рождения',
            'email' => 'Электронная почта (Email)',
            'sex' => 'Пол',
            'passport_number' => 'Серия Паспорта',
            'where_passport' => 'Кем выдан паспорт',
            'date_passport' => 'Дата выдачи паспорта',
            'id_city' => 'Город или регион',
            'sp_int' => 'Sp Консультант',
            'sp_unique' => 'Sp Инвестора',
            'phone' => 'Мобильный телефон',
            'inn' => 'ИНН',
            'datecreate' => 'Datecreate',
            'lastupdate' => 'Lastupdate',
            'role' => 'Роль в системе',
            'status' => 'Status',
            'fio' => 'Ф.И.О',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBalances0()
    {
        return $this->hasMany(Balance::className(), ['id_kassir' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCity()
    {
        return $this->hasOne(City::className(), ['id' => 'id_city']);
    }

    public function getLevel()
    {
        return $this->hasMany(Level::className(), ['id_user' => 'id']);
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Balance;
use app\models\City;
use app\models\Control;
use app\models\Date;
use app\models\Deals;
use app\models\Level;
use app\models\User;
use Yii;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    public $layout = "admin";

    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','index','update','view','account','agreement','balance','invited','gave','depted','payments','kassir','reports','pay','deal','direct','add','unpay','myrecieve','regions','region'],
                'rules' => [
                    [
                        'actions' => ['create','index','update','view','account','agreement','gave','balance','depted','payments','kassir','reports','pay','deals','add','region'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserAdmin(Yii::$app->user->identity->login);
                        }
                    ],
                    [
                        'actions' => ['create','index','upd','view','account','agreement','gave','balance','depted','payments','kassir','reports','pay','index','deals','add','region'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,4);
                        }
                    ],
                    [
                        'actions' => ['view','account','gave','balance','payments','pay','unpay','myrecieve','regions'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,2);
                        }
                    ],
                    [
                        'actions' => ['invited','account','create','view','update','deal','agreement','direct'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,1);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all Users models.
     * @return mixed
     */

    public function actionDeals($id){
        $users=Users::findOne($id);

       return $this->render('deals',['user'=>$users]);
    }

    public function actionRegion(){
        $city=City::find();

        $dataProvider = new ActiveDataProvider([
            'query' =>$city
        ]);

        return $this->render('regions', [
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionIndex($type=null)
    {

        if(!is_null($type))
            $query=Users::find()->where(['not in', 'id', Yii::$app->user->identity->getId()])->andWhere(['not in', 'role', [4,3]])->andWhere(['role'=>$type])->orderBy(['datecreate'=>SORT_DESC]);
        else
            $query=Users::find()->where(['not in', 'id', Yii::$app->user->identity->getId()])->andWhere(['not in', 'role', [4,3]])->orderBy(['datecreate'=>SORT_DESC]);

        $dataProvider = new ActiveDataProvider([
            'query' =>$query
            ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRegions()
    {
        $this->render('regions');
    }



    public function actionAgreement($id)
    {

        $model = new Deals();
        $model->id_level = $id;
        $model->deal_id = rand(10000000, 1000000000);
        $model->datecreate = time();
        $model->lastupdate = time();
        $model->status = 1;
        $find = Deals::find()->where(['id_level' => $id])->one();
        if (empty($find)) {
            if ($model->save())
                return $this->redirect(['users/invited']);
        } else return $this->redirect(['users/invited']);
    }

    public function actionBalance()
    {
        $balance=Balance::findAll(['status'=>1]);
        $bal=Balance::findBySql("SELECT SUM(money) as money,id_kassir FROM balance GROUP BY id_kassir ORDER BY money DESC")->all();
        return $this->render('balance',['deals'=>$balance,'bal'=>$bal]);
    }

    public function actionDepted()
    {
        return $this->render('depted');
    }

    public function actionKassir()
    {
        $kassir=Users::find()->where(['role'=>2])->all();
        return $this->render('kassir',['kassir'=>$kassir]);
    }

    public function actionMyrecieve()
    {
        $deals=Balance::find()->where(['id_kassir'=>Yii::$app->user->identity->getId()])->all();
        return $this->render('recieve',['deals'=>$deals]);
    }

    public function actionPayments()
    {

        $deals = \app\models\Deals::find()->alias('t1')->where(['status'=>1])->andWhere(['not exists', \app\models\Balance::find()->alias('t2')->select('deals_id')->andWhere('t2.deals_id = t1.id')])->all();
        //var_dump($deals);
        return $this->render('payments');
    }

    public function actionPay($id)
    {
        $model = new Balance();
        $deals = $this->findDeals($id);
            $model->id_kassir = Yii::$app->user->identity->getId();
            $model->deals_id = $deals->id;
            switch ($deals->idLevel->level) {
                case 1:
                    $model->money = 1000;
                    break;
                case 2:
                    $model->money = 500;
                    break;
                case 3:
                    $model->money = 500;
                    break;
                case 4:
                    $model->money = 500;
                    break;
            }
            $model->datecreate = time();
            $model->lastupdate = time();
            $model->status = 1;
                if($model->save())
                return $this->redirect(['users/payments']);
    }

    public function actionReports($type = null)
    {
        switch ($type) {
            case 'present':

                if (isset($_GET['id'])) {
                    var_dump($_GET['id']);
                    $user = Users::findOne($_GET['id']);
                    $all = Level::find()->where(['sp_int' => $user->level->sp_unique])->all();
                    return $this->render('includes/investor', ['all' => $all]);
                } else {
                    $users = Users::find()->where(['role' => 1])->all();
                    return $this->render('includes/present', ['users' => $users]);
                }
                break;
            case 'date':
                if ((isset($_POST['date_start']) && isset($_POST['date'])) or isset($_POST['statr_date']) or isset($_POST['date_end'])) {
                    Yii::$app->session->set('date_start', $_POST['date_start']);
                    Yii::$app->session->set('date_end', $_POST['date_end']);
                    $balance = Balance::find()->where(['between', 'datecreate', strtotime(Yii::$app->session->get('date_start')), strtotime(Yii::$app->session->get('date_end'))])->orderBy(['datecreate' => SORT_DESC])->all();
                    return $this->render('includes/date', ['balance' => $balance]);
                }
                return $this->render('includes/date');
                break;
            case 'dose':
                return $this->render('includes/dose');
                break;

            case 'goo':
                if (isset($_GET['sp'])) {
                    $level = Level::find()->where(['sp_int' => $_GET['sp']])->all();
                    return $this->render('includes/presentator', ['level' => $level]);
                }
                break;
            case 'region':
                $city = City::find()->all();
                return $this->render('includes/region', ['city' => $city]);
                break;
            default:
                $users = Users::find()->where(['role' => 1])->all();
                return $this->render('includes/present', ['users' => $users]);
        }

    }


    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionAccount()
    {

        return $this->render('dashboard');
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        $model->scenario = "registrUser";
        $model->datecreate = time();
        $model->lastupdate = time();
        if (Yii::$app->user->identity->role == 1)
            $model->role = 0;
        $model->status = 1;

        if ($model->load(Yii::$app->request->post())) {
            $check = Control::getUserLike($model->name, $model->lname, $model->oname, $model->inn, $model->date_birth);
            if (empty($check)) {
                //var_dump($check);
                $model->login = $this->generateRandomString();

views/users/includes/date.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Поиска по дате';
$this->params['breadcrumbs'][] = ['label'=>$this->title,'template'=>"<li class='list-inline-item'>{link}</li>"];
?>
<?php Pjax::begin(['enablePushState'=>true,'timeout'=>10000,'class'=>'']); ?>
<div id="reload" class="row">
    <div class="col-md-2">
        <div class="card">
            <div class="card-header">
                <strong>Block Level Buttons </strong>
            </div>
            <div class="card-body" style="color: #fff;">
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'present']) ?>" class="btn btn-primary btn-lg btn-block">Презентаторы</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'date']) ?>" class="btn btn-success btn-lg btn-block">Поиск по дате</a>

                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'dose']) ?>" class="btn btn-primary btn-lg btn-block">Досье</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'region']) ?>" class="btn btn-primary btn-lg btn-block">Регионы</a>
<!--                <a type="button" href="--><?//= \yii\helpers\Url::to(['users/reports','type'=>'investor']) ?><!--" class="btn btn-primary btn-lg btn-block">Sp инвестора</a>-->
            </div>
        </div>
    </div>
    <div class="col">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Просмотр отчета по периодам баланса </strong>
            </div>
            <div class="card-body" >
                <?php $form = ActiveForm::begin(); ?>
                <div class="row">

                    <div class="col-lg-5">
                        <form method="GET" action="<?= \yii\helpers\Url::to(['users/report']) ?>">
                        <div class="form-group field-users-lname">
                            <label class="control-label" for="users-lname">С периода</label>
                         <input type="date" id="users-lname" class="form-control" name="date_start" maxlength="50">

                            <div class="help-block"></div>
                        </div>                </div>
                    <div class="col-lg-5">
                        <div class="form-group field-users-lname">
                            <label class="control-label" for="users-lname">до</label>
                            <input type="date" id="users-lname" class="form-control" name="date_end" maxlength="50">

                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <input type="submit" value="Искать" class="btn btn-primary btn-block" style="line-height: 3;margin-top: 20px;">
                    </div>
                    </form>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

        <?php if(isset($balance)){ ?>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Просмотр отчета по периодам баланса </strong>
                </div>
                <div class="card-body" >
                    <div class="table-responsive table--no-card m-b-30">
                        <table class="table table-borderless table-striped table-earning">
                            <thead>
                            <tr>
                                <th>Ф.И.О</th>
                                <th class="text-right">Телефон</th>
                                <th class="text-right">Договор</th>
                                <th class="text-right">Деньги</th>
                                <th class="text-right">Время</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $s=0;
                            //                echo '<pre>';
                            //                var_dump($baleals);
                            //                echo '</pre>';
                            foreach ($balance as $bal){
                                echo "<tr>";
                                echo "<td class='text-left'>".$bal->deals->idLevel->idUser->name." ".$bal->deals->idLevel->idUser->lname." ".$bal->deals->idLevel->idUser->oname."</td>";
                                echo "<td class='text-right'>".$bal->deals->idLevel->idUser->phone."</td>";
                                echo "<td class='text-right'>".$bal->deals->deal_id."</td>";
                                echo "<td class='text-right'>".$bal->money."</td>";
                                echo "<td class='text-right'>".date('d-M-Y',$bal->datecreate)."</td>";
                                $s=$s+$bal->money;
                                echo  '</td>';
                                echo '</tr>';
                            }

                            ?>
                            <tr>
                                <td style="background: black;color: white;font-size: 20px;font-weight: 500;">&nbsp;</td>
                                <td style="background: black;color: white;font-size: 20px;font-weight: 500;">&nbsp;</td>
                                <td class='text-right' style="background: black;color: white;font-size: 20px;font-weight: 500;">Итог</td>
                                <td class='text-right' style="background: black;color: white;font-size: 20px;font-weight: 500;"><?= $s ?></td>
                                <td style="background: black;color: white;font-size: 20px;font-weight: 500;">&nbsp;</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <?php } ?>
        <?php Pjax::end(); ?>

views/users/includes/dose.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Досье';
$this->params['breadcrumbs'][] = ['label'=>$this->title,'template'=>"<li class='list-inline-item'>{link}</li>"];
?>
<?php Pjax::begin(['enablePushState'=>true,'timeout'=>10000,'class'=>'']); ?>
<div id="reload" class="row">
    <div class="col-md-2">
        <div class="card">
            <div class="card-header">
                <strong>Block Level Buttons </strong>
            </div>
            <div class="card-body" style="color: #fff;">
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'present']) ?>" class="btn btn-primary btn-lg btn-block">Презентаторы</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'date']) ?>" class="btn btn-primary btn-lg btn-block">Поиск по дате</a>

                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'dose']) ?>" class="btn btn-success btn-lg btn-block">Досье</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'region']) ?>" class="btn btn-primary btn-lg btn-block">Регионы</a>
<!--                <a type="button" href="--><?//= \yii\helpers\Url::to(['users/reports','type'=>'investor']) ?><!--" class="btn btn-primary btn-lg btn-block">Sp инвестора</a>-->
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <strong>Block Level Buttons </strong>
                <small>Use this class
                    <code>.btn-block</code>
                </small>
            </div>
            <div class="card-body" >
                На стадии разработки
            </div>
        </div>
    </div>
</div>
<?php Pjax::end(); ?>

views/users/includes/presentator.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Презентатор';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['reports', 'type' => "present"]];
$this->params['breadcrumbs'][] = ['label'=>'Изменить','template'=>"<li class='list-inline-item'>{link}</li>"];
?>
<?php Pjax::begin(['enablePushState'=>true,'timeout'=>10000,'class'=>'']); ?>
<div id="reload" class="row">
    <div class="col-md-2">
        <div class="card">
            <div class="card-header">
                <strong>Block Level Buttons </strong>
            </div>
            <div class="card-body" style="color: #fff;">
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'present']) ?>" class="btn btn-success btn-lg btn-block">Презентаторы</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'date']) ?>" class="btn btn-primary btn-lg btn-block">Поиск по дате</a>

                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'dose']) ?>" class="btn btn-primary btn-lg btn-block">Досье</a>
                <a type="button" href="<?= \yii\helpers\Url::to(['users/reports','type'=>'region']) ?>" class="btn btn-primary btn-lg btn-block">Регионы</a>
<!--                <a type="button" href="--><?//= \yii\helpers\Url::to(['users/reports','type'=>'investor']) ?><!--" class="btn btn-success btn-lg btn-block">Sp инвестора</a>-->
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                <strong>Block Level Buttons </strong>
            </div>
            <div class="card-body" >
                <?php if(isset($level)){ ?>
                <div class="table-responsive table--no-card m-b-30">
                    <table class="table table-borderless table-striped table-earning">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Ф.И.О</th>
                            <th class="text-right">Телефон</th>
                            <th class="text-right">Sp Консултантов</th>
                            <th class="text-right">Уровень</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        //                echo '<pre>';
                        //                var_dump($l->idUsereals);
                        //                echo '</pre>';
                        $i=1;
                        foreach ($level as $l){
                            echo "<tr>";
                            echo "<td>".$i++."</td>";
                            echo "<td class='text-left'><a href='".\yii\helpers\Url::to(['users/deals','id'=>$l->idUser->id])."' >".$l->idUser->name." ".$l->idUser->lname." ".$l->idUser->oname."</a></td>";
                            echo "<td class='text-right'>".$l->idUser->phone."</td>";
                            echo "<td class='text-right'>".$l->idUser->level[0]->sp_unique."</td>";
                            echo "<td class='text-right'>".$l->level."</td>";
                            echo  '</td>';
                            echo '</tr>';
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            <?php }?>
            </div>
        </div>
    </div>
</div>
<?php Pjax::end(); ?>