models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use yii\db\ActiveRecord;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;

    const ROLE_USER=1;
    const ROLE_ADMISION=2;
    const ROLE_ADMIN=3;
    const ROLE_SUPER_ADMIN=4;

    const SALT="HacNNdqKYmceDFHHDGBVIvcuLXJPfPUH";

    public static function tableName()
    {
        return 'users';
    }
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return self::findOne(array('id'=>$id));
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    public static function isUserAdmin($username)
    {
        if (static::findOne(['login' => $username, 'role' => self::ROLE_ADMIN]))
            return true;

        return false;
    }

    public static function isUserOrAdmission($username,$role)
    {
        switch ($role){
            case 1:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_USER]))
                    return true;
                break;
            case 2:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_ADMISION]))
                    return true;
                break;
            case 4:
                if (static::findOne(['login' => $username, 'role' => self::ROLE_SUPER_ADMIN]))
                    return true;
                break;
            default: return false;
            break;
        }
    }


    public static function findByLogin($login)
    {
        //return User::find()->where(['email' => $email, 'status' => self::STATUS_ACTIVE])->one();
        return self::findOne(['login' => $login]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(['login' => $username]);
//        foreach (self::$users as $user) {
//            if (strcasecmp($user['username'], $username) === 0) {
//                return new static($user);
//            }
//        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        //return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        if (Yii::$app->getSecurity()->validatePassword($password, $this->password))
            return true;
        return false;

    }

    public function getFullname()
    {
        $profile = static::find()->where(['id'=>Yii::$app->user->identity->id])->one();
        if ($profile !=null)
            return $profile->name.' '.$profile->lname.' '.$profile->oname;
        else return "Not Autorized";
        return false;
    }

    public function getLevel()
    {
        return $this->hasMany(Level::className(), ['id_user' => 'id']);
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $genauto
 * @property string $name
 * @property string $lname
 * @property string $oname
 * @property string $date_birth
 * @property string $email
 * @property integer $sex
 * @property string $passport_number
 * @property string $where_passport
 * @property string $date_passport
 * @property integer $id_city
 * @property integer $sp_int
 * @property integer $sp_unique
 * @property integer $datecreate
 * @property integer $lastupdate
 * @property integer $role
 * @property integer $status
 *
 * @property Balance[] $balances
 * @property Balance[] $balances0
 * @property City $idCity
 */
class Users extends \yii\db\ActiveRecord
{
    public $sp_unique;
    public $sp_int;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login', 'password', 'name', 'lname', 'datecreate', 'lastupdate', 'role', 'status','genauto','email'], 'required','on'=>'registrAdmin'],
            [['sex', 'id_city', 'sp_int', 'sp_unique', 'datecreate', 'lastupdate', 'role', 'status','passport_number','where_passport','phone','date_birth','email','date_passport','login','address', 'name', 'lname'], 'required','on'=>'registrUser'],
            [['sex', 'id_city', 'datecreate', 'lastupdate', 'role', 'status','passport_number','where_passport','phone','date_birth','email','date_passport','login','address', 'name', 'lname'], 'required','on'=>'updateUser'],
            [['date_birth', 'email', 'date_passport'], 'safe'],
            [['email'], 'email'],
            ['login', 'unique'],
            ['email', 'unique'],
            ['inn', 'unique'],
            [['date_birth','date_passport'], 'date', 'format' => 'yyyy-mm-dd','on'=>'registrUser'],
            [['date_birth','date_passport'], 'date', 'format' => 'yyyy-mm-dd','on'=>'updateUser'],

            [['sex', 'id_city', 'sp_int', 'sp_unique', 'datecreate', 'lastupdate', 'role', 'status','inn'], 'integer'],
            [['login', 'name', 'lname', 'oname','phone'], 'string', 'max' => 50],
            [['password','genauto','address'], 'string', 'max' => 255],
            [['passport_number'], 'string', 'max' => 20],
            [['where_passport','email'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Логин',
            'password' => 'Пароль',
            'genauto' => 'Пароль',
            'address' => 'Адрес',
            'name' => 'Имя',
            'lname' => 'Фамилия',
            'oname' => 'Отчества',
            'date_birth' => 'День рождения',
            'email' => 'Электронная почта (Email)',
            'sex' => 'Пол',
            'passport_number' => 'Серия Паспорта',
            'where_passport' => 'Кем выдан паспорт',
            'date_passport' => 'Дата выдачи паспорта',
            'id_city' => 'Город или регион',
            'sp_int' => 'Sp Консультант',
            'sp_unique' => 'Sp Инвестора',
            'phone' => 'Мобильный телефон',
            'inn' => 'ИНН',
            'datecreate' => 'Datecreate',
            'lastupdate' => 'Lastupdate',
            'role' => 'Роль в системе',
            'status' => 'Status',
            'fio' => 'Ф.И.О',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBalances0()
    {
        return $this->hasMany(Balance::className(), ['id_kassir' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCity()
    {
        return $this->hasOne(City::className(), ['id' => 'id_city']);
    }

    public function getLevel()
    {
        return $this->hasMany(Level::className(), ['id_user' => 'id']);
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Balance;
use app\models\City;
use app\models\Control;
use app\models\Date;
use app\models\Deals;
use app\models\Level;
use app\models\User;
use Yii;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    public $layout = "admin";

    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create','index','update','view','account','agreement','balance','invited','gave','depted','payments','kassir','reports','pay','deal','direct','add','unpay','myrecieve','regions','region'],
                'rules' => [
                    [
                        'actions' => ['create','index','update','view','account','agreement','gave','balance','depted','payments','kassir','reports','pay','deals','add','region'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserAdmin(Yii::$app->user->identity->login);
                        }
                    ],
                    [
                        'actions' => ['create','index','upd','view','account','agreement','gave','balance','depted','payments','kassir','reports','pay','index','deals','add','region'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,4);
                        }
                    ],
                    [
                        'actions' => ['view','account','gave','balance','payments','pay','unpay','myrecieve','regions'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,2);
                        }
                    ],
                    [
                        'actions' => ['invited','account','create','view','update','deal','agreement','direct'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\models\User::isUserOrAdmission(Yii::$app->user->identity->login,1);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all Users models.
     * @return mixed
     */

    public function actionDeals($id){
        $users=Users::findOne($id);

       return $this->render('deals',['user'=>$users]);
    }

    public function actionRegion(){
        $city=City::find();

        $dataProvider = new ActiveDataProvider([
            'query' =>$city
        ]);

        return $this->render('regions', [
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionIndex($type=null)
    {

        if(!is_null($type))
            $query=Users::find()->where(['not in', 'id', Yii::$app->user->identity->getId()])->andWhere(['not in', 'role', [4,3]])->andWhere(['role'=>$type])->orderBy(['datecreate'=>SORT_DESC]);
        else
            $query=Users::find()->where(['not in', 'id', Yii::$app->user->identity->getId()])->andWhere(['not in', 'role', [4,3]])->orderBy(['datecreate'=>SORT_DESC]);

        $dataProvider = new ActiveDataProvider([
            'query' =>$query
            ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRegions()
    {
        $this->render('regions');
    }



    public function actionAgreement($id)
    {

        $model = new Deals();
        $model->id_level = $id;
        $model->deal_id = rand(10000000, 1000000000);
        $model->datecreate = time();
        $model->lastupdate = time();
        $model->status = 1;
        $find = Deals::find()->where(['id_level' => $id])->one();
        if (empty($find)) {
            if ($model->save())
                return $this->redirect(['users/invited']);
        } else return $this->redirect(['users/invited']);
    }

    public function actionBalance()
    {
        $balance=Balance::findAll(['status'=>1]);
        $bal=Balance::findBySql("SELECT SUM(money) as money,id_kassir FROM balance GROUP BY id_kassir ORDER BY money DESC")->all();
        return $this->render('balance',['deals'=>$balance,'bal'=>$bal]);
    }

    public function actionDepted()
    {
        return $this->render('depted');
    }

    public function actionKassir()
    {
        $kassir=Users::find()->where(['role'=>2])->all();
        return $this->render('kassir',['kassir'=>$kassir]);
    }

    public function actionMyrecieve()
    {
        $deals=Balance::find()->where(['id_kassir'=>Yii::$app->user->identity->getId()])->all();
        return $this->render('recieve',['deals'=>$deals]);
    }

    public function actionPayments()
    {

        $deals = \app\models\Deals::find()->alias('t1')->where(['status'=>1])->andWhere(['not exists', \app\models\Balance::find()->alias('t2')->select('deals_id')->andWhere('t2.deals_id = t1.id')])->all();
        //var_dump($deals);
        return $this->render('payments');
    }

    public function actionPay($id)
    {
        $model = new Balance();
        $deals = $this->findDeals($id);
            $model->id_kassir = Yii::$app->user->identity->getId();
            $model->deals_id = $deals->id;
            switch ($deals->idLevel->level) {
                case 1:
                    $model->money = 1000;
                    break;
                case 2:
                    $model->money = 500;
                    break;
                case 3:
                    $model->money = 500;
                    break;
                case 4:
                    $model->money = 500;
                    break;
            }
            $model->datecreate = time();
            $model->lastupdate = time();
            $model->status = 1;
                if($model->save())
                return $this->redirect(['users/payments']);
    }

    public function actionReports($type = null)
    {
        switch ($type) {
            case 'present':

                if (isset($_GET['id'])) {
                    var_dump($_GET['id']);
                    $user = Users::findOne($_GET['id']);
                    $all = Level::find()->where(['sp_int' => $user->level->sp_unique])->all();
                    return $this->render('includes/investor', ['all' => $all]);
                } else {
                    $users = Users::find()->where(['role' => 1])->all();
                    return $this->render('includes/present', ['users' => $users]);
                }
                break;
            case 'date':
                if ((isset($_POST['date_start']) && isset($_POST['date'])) or isset($_POST['statr_date']) or isset($_POST['date_end'])) {
                    Yii::$app->session->set('date_start', $_POST['date_start']);
                    Yii::$app->session->set('date_end', $_POST['date_end']);
                    $balance = Balance::find()->where(['between', 'datecreate', strtotime(Yii::$app->session->get('date_start')), strtotime(Yii::$app->session->get('date_end'))])->orderBy(['datecreate' => SORT_DESC])->all();
                    return $this->render('includes/date', ['balance' => $balance]);
                }
                return $this->render('includes/date');
                break;
            case 'dose':
                return $this->render('includes/dose');
                break;

            case 'goo':
                if (isset($_GET['sp'])) {
                    $level = Level::find()->where(['sp_int' => $_GET['sp']])->all();
                    return $this->render('includes/presentator', ['level' => $level]);
                }
                break;
            case 'region':
                $city = City::find()->all();
                return $this->render('includes/region', ['city' => $city]);
                break;
            default:
                $users = Users::find()->where(['role' => 1])->all();
                return $this->render('includes/present', ['users' => $users]);
        }

    }


    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionAccount()
    {

        return $this->render('dashboard');
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        $model->scenario = "registrUser";
        $model->datecreate = time();
        $model->lastupdate = time();
        if (Yii::$app->user->identity->role == 1)
            $model->role = 0;
        $model->status = 1;

        if ($model->load(Yii::$app->request->post())) {
            $check = Control::getUserLike($model->name, $model->lname, $model->oname, $model->inn, $model->date_birth);
            if (empty($check)) {
                //var_dump($check);
                $model->login = $this->generateRandomString();

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Создать участника';
$this->params['breadcrumbs'][] = ['label'=>$this->title,'template'=>"<li class='list-inline-item'>{link}</li>"];
?>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title"><?= Html::encode($this->title) ?></strong>
            </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

        </div>
    </div>
</div>

views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = ['label'=>$this->title,'template'=>"<li class='list-inline-item'>{link}</li>"];
?>
<style>
    .table a{
        font-size: 19px;
        padding-right:3px;
    }
</style>
<script type="text/javascript">

    function update(id) {
        var data = $('#check_'+id).val();
        $.ajax({
            type: 'POST',
            url: "<?php echo Url::to(['users/status']); ?>",
            cache: false,
            data: {id:id,value:data},
            error: function () {

            },
            beforeSend: function () {
                $('checkbox').attr('disabled', 'disabled');
            },
            success: function (data) {
                $('checkbox').removeAttr('disabled');
                //location.reload();
                $.pjax.reload({container: '#pjax-container'});
            }
        })
    }

</script>
<div class="row">
    <div class="col-md-12 ">
        <div class="row"><div class="col-md-6"><div class="card-body">
                    <a class="btn <?= $_GET['type']==0 ? 'btn-success' : 'btn-primary' ?>" href="<?= Url::to(['users/index','type'=>0]) ?>">Инвесторы</a>
                    <a class="btn <?= $_GET['type']==1  ? 'btn-success' : 'btn-primary' ?>" href="<?= Url::to(['users/index','type'=>1]) ?>">Презентаторы</a>
                    <a class="btn <?= $_GET['type']==2 ? 'btn-success' : 'btn-primary' ?>" href="<?= Url::to(['users/index','type'=>2]) ?>">Кассиры</a>
                    <a class="btn <?= $_GET['type']==3 ? 'btn-success' : 'btn-primary' ?>" href="<?= Url::to(['users/index','type'=>3]) ?>">Админы</a></div></div>
        <div class="col-md-6">
            <?php if(Yii::$app->user->identity->role==3 or Yii::$app->user->identity->role==4) echo '<div class="card-body">
                                        <a href="'.Url::to(["users/add","type"=>1]).'" class="btn btn-primary">Добавить Презентатора</a> <a href="'.Url::to(["users/add","type"=>2]).'" class="btn btn-secondary">Добавить Кассира</a>';
            if(Yii::$app->user->identity->role==4) echo '<a href="'.Url::to(["users/add","type"=>3]).'" class="btn btn-success">Добавить Администратора</a>' ;
            echo  '</div>';?>
        </div></div>
        <?php Pjax::begin(['id' => 'pjax-container']); ?>
        <div class="table-responsive table-responsive table-responsive-data3" style="margin-bottom: 25px;">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => [
                    'class' => 'table table-borderless table-data3'
                ],
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    //'id',
                    //'login',
                    //'genauto',
                    [
                        'attribute' => 'fio',
                        'format' => 'raw',
                        'value' => function ($model) {
                            return $model->name.' '.$model->lname.' '.$model->oname;
                        },
                    ],
                    'login',
                    'genauto',
                    [
                        'attribute'=>'date_birth',
                        'value'=>function($model){
                            return \app\models\Control::getDate($model->date_birth);
                        },
                        'format'=>'raw'
                    ],
                    'inn',
                    [
                        'attribute' => 'status',
                        'format' => 'raw',
                        'value' => function ($model) {
                            if(Yii::$app->user->identity->role!=1)


                                if ($model->status === 0) {
                                    return '<label id="form_'.$model->id.'" class="switch">
                                        <input id="check_'.$model->id.'" onclick="update('.$model->id.')" value=1 type="checkbox">
                                          <span class="slider round"></span>
                                        </label>'; // "x" icon in red color
                                }elseif($model->status==1){
                                    return '<label id="form_'.$model->id.'"  class="switch">
                                        <input id="check_'.$model->id.'" onclick="update('.$model->id.')" value=0 type="checkbox" checked>
                                          <span class="slider round"></span>
                                        </label>'; // check icon
                                }else{
                                    return '<label  class="switch">
                                        <input  value=0 type="checkbox" disabled>
                                          <span class="slider round"></span>
                                        </label>';
                                }
                        },
                    ],
                    [
                        'attribute' => 'role',
                        'format' => 'raw',
                        'value' => function ($model) {
                            switch ($model->role){
                                case 0:
                                    return '<h3><span class="badge badge-light">Инвестор</span></h3>';
                                case 1:
                                    return '<h3><span class="badge badge-secondary">Презентатор</span></h3>';
                                    break;
                                case 2:
                                    return '<h3><span class="badge badge-primary">Кассир</span></h3>';
                                    break;
                                case 3:
                                    return '<h3><span class="badge badge-warning">Админ</span></h3>';
                                    break;
                            }
                        },
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Actions',
                        'headerOptions' => ['style' => 'color:#337ab7'],
                        'template' => '{agree}{view}{update}',
                        'buttons' => [
                            'agree' => function ($url, $model) {
                                if($model->role==0)
                                return Html::a('<button type="button" class="btn btn-success m-l-10"><span class="fa fa-list-alt"></span></button>', $url, [
                                    'title' => Yii::t('app', 'Договор'),
                                ]);
                            },
                            'view' => function ($url, $model) {
                                if($model->status==1){
                                return Html::a('<button type="button" class="btn btn-info m-l-10"><span class="fa fa-eye"></span></button>', $url, [
                                    'title' => Yii::t('app', 'Просмотр'),
                                ]);
                                }elseif($model->status==2){
                                    return Html::a('<button type="button" class="btn btn-success m-l-10"><span class="fa fa-eye"></span></button>', $url, [
                                        'title' => Yii::t('app', 'Просмотр'),
                                    ]);
                                }else{
                                    return Html::a('<button type="button" class="btn btn-danger m-l-10"><span class="fa fa-eye"></span></button>', $url, [
                                        'title' => Yii::t('app', 'Просмотр'),
                                    ]);
                                }
                            },

                            'update' => function ($url, $model) {
                                $now = strtotime("-10 minutes");
                                if(Yii::$app->user->identity->role==1){
                                    if ($now > $model->datecreate) {

                                    }else
                                        return Html::a('<button type="button" class="btn btn-primary m-l-10"><span class="zmdi zmdi-edit"></span></button>', $url, ['class'=>'item' ,
                                            'title' => Yii::t('app', 'update'),
                                        ]);
                                }else{

                                return Html::a('<button type="button" class="btn btn-primary m-l-10"><span class="zmdi zmdi-edit"></span></button>', $url, ['class'=>'item' ,
                                    'title' => Yii::t('app', 'Изменить'),
                                ]);
                                }
                            },

                        ],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            if ($action === 'agree') {
                                $url =Url::to(['users/deals','id'=>$model->id]);
                                return $url;
                            }
                            if ($action === 'view') {
                                $url =Url::to(['users/view','id'=>$model->id]);
                                return $url;
                            }

                            if ($action === 'update') {
                                $url =Url::to(['users/upd','id'=>$model->id,'type'=>$model->role]);
                                return $url;
                            }
                        }
                    ],
                ],
            ]); ?>
        </div>
        <?php Pjax::end(); ?>
    </div>
</div>

views/users/payments.php
<?php

use app\models\Users;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Платежи';
$this->params['breadcrumbs'][] = ['label'=>$this->title,'template'=>"<li class='list-inline-item'>{link}</li>"];
$deal=Users::find()->where(['role'=>1])->all();


?>
<div class="row">
    <div class="col-lg-12">
        <?php
        foreach ($deal as $pre){
            $deals=\app\models\Control::getAllDeptors($pre->level[0]->sp_unique);
            if($deals!=null){
            echo '
                                <div class="card">
                                    <div class="card-header bg-success">
                                        <a class="card-title text-light"><a href="'.\yii\helpers\Url::to(['users/view','id'=>$pre->id]).'" style="color: #fff; text-decoration: none;font-weight: 700">'.$pre->lname.' '.$pre->name.' '.$pre->oname.'</a></strong>
                                    </div>
                                    ';

            ?>

            <table class="table table-borderless table-striped table-earning">
                <thead>
                <tr>
                    <th>Ф.И.О</th>
                    <th class="text-right">Уровень</th>
                    <th class="text-right">Инн</th>
                    <th class="text-right">Договор</th>
                    <th class="text-right">Деньги</th>
                    <th class="text-right">Время регистрации</th>
                    <th class="text-right">Операции</th>
                </tr>
                </thead>
                <tbody>
                <?php
               // echo '<pre>';
                //                var_dump($deals);
                //                echo '</pre>';
                foreach ($deals as $d){
                    $balance=\app\models\Control::checkForBalance($d->id);


                    echo "<tr>";
                    echo "<td>".$d->idLevel->idUser->name." ".$d->idLevel->idUser->lname." ".$d->idLevel->idUser->oname."</td>";
                    echo "<td class='text-right'>".$d->idLevel->level."</td>";
                    echo "<td class='text-right'>".$d->idLevel->idUser->inn."</td>";
                    echo "<td class='text-right'>".$d->deal_id."</td>";
                    echo "<td class='text-right'>".\app\models\Control::getMoneyFor($d->idLevel->level)."</td>";

                    echo "<td class='text-right'>".date('d-M-Y',$d->datecreate)."</td>";
                    echo '<td class="text-right">';
                    if($balance!=1) echo '<a href="'.\yii\helpers\Url::to(['users/pay','id'=>$d->id]).'" class="btn btn-primary btn-sm">
                                             Оплатить
                                        </a>';
                    else{
                        echo '<a href="'.\yii\helpers\Url::to(['users/cvitance','id'=>$d->id]).'" class="btn btn-warning btn-sm m-r-10">
                      <i class="fa fa-list-ol"></i> Квитанция
                      </a>';
                        echo '<a href="'.\yii\helpers\Url::to(['users/unpay','id'=>$d->id]).'" class="btn btn-danger btn-sm">
                      <i class="fa fa-trash"></i> Отмена оплаты
                      </a>';
                    }
                    echo  '</td>';
                    echo '</tr>';
                }
                ?>
                </tbody>
            </table>

            <?php
                         echo        '</div>
                                
                            ';
        }
        }
        ?>
        <div class="table-responsive table--no-card m-b-30">



        </div>
    </div>

</div>